#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c $XDG_CONFIG_HOME/sxhkd/sxhkdrc $XDG_CONFIG_HOME/bspwm/sxhkdrc &

bspc config border_width         2
bspc config window_gap           36
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config focused_border_color "#A996E8"
bspc config presel_feedback_color "#807e7e"
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc rule -a mpv state=floating
bspc rule -a Sxiv state=floating
bspc rule -a Zathura state=tiled
bspc rule -a "*:alacritty:cava" state=floating layer=above

$XDG_CONFIG_HOME/polybar/launch.sh
